image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ./gradlew build # сборка проекта
  - java -jar ./build/libs/my-app.jar # запуск приложения
  - ./gradlew test --info -Dselenide.headless=true # запуск тестов