image: Ubuntu

stack: jdk11

branches:
  only:
    - master

before_build:
  # Установка JDK и Gradle
  - apt-get update
  - apt-get install -y openjdk-11-jdk
  - wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
  - unzip -qq gradle-7.2-bin.zip
  - export PATH=$PATH:`pwd`/gradle-7.2/bin

build_script:
  # Сборка проекта и запуск SUT
  - gradle build
  - java -jar ./build/libs/app-ibank.jar -P:profile=test &

test_script:
  # Запуск тестов
  - gradle test --info -Dselenide.headless=true
