image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - ./gradlew test --info -Dselenide.headless=true # запускаем тест, флаг --info позволяет выводить больше информации

install:
  - chmod +x gradlew
